/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TinhLuongGrossNetRouteImport } from './routes/tinh-luong-gross-net'
import { Route as IndexRouteImport } from './routes/index'

const TinhLuongGrossNetRoute = TinhLuongGrossNetRouteImport.update({
  id: '/tinh-luong-gross-net',
  path: '/tinh-luong-gross-net',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tinh-luong-gross-net': typeof TinhLuongGrossNetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tinh-luong-gross-net': typeof TinhLuongGrossNetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tinh-luong-gross-net': typeof TinhLuongGrossNetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tinh-luong-gross-net'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tinh-luong-gross-net'
  id: '__root__' | '/' | '/tinh-luong-gross-net'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TinhLuongGrossNetRoute: typeof TinhLuongGrossNetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tinh-luong-gross-net': {
      id: '/tinh-luong-gross-net'
      path: '/tinh-luong-gross-net'
      fullPath: '/tinh-luong-gross-net'
      preLoaderRoute: typeof TinhLuongGrossNetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TinhLuongGrossNetRoute: TinhLuongGrossNetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
